### PR TITLE
LuaServer: add method for mimetype consistency check

### LINKED ISSUE #316: mimetype_consistency should also work with non-image files
Currently. this method is implemented as `SipiImage::checkMimeTypeConsistency` and works only for images. It should be made more generic so  that it also works for non-image files.

### PR DESCRIPTION
**Pull request by tobiasschweizer**
closes #316

### CODE REVIEW

File: shttps/LuaServer.cpp [hunk 1]
```diff
@@ -2305,6 +2305,52 @@ namespace shttps {
...
+        std::cout << filepath << std::endl;
+        std::cout << given_mimetype << std::endl;
+        std::cout << given_filename << std::endl;
+
+        // do the consistency check
+
+        bool check;
+
+        /*try {
+            check = SipiImage::checkMimeTypeConsistency(*filepath, given_mimetype, given_filename);
```
Comment (tobiasschweizer) [inline shttps/LuaServer.cpp]: @lrosenth How can I get access to the static method of `SipiImage`? I tried to include `SipiImage.h` but it did not work.

File: src/SipiLua.cpp [hunk 2]
```diff
@@ -645,7 +646,7 @@ namespace Sipi {
         bool check;
 
         try {
-            check = img->image->checkMimeTypeConsistency(*path, given_mimetype, given_filename);
+            //check = MimetypeCheck::checkMimeTypeConsistency(*path, given_mimetype, given_filename);
```
Comment (tobiasschweizer) [inline src/SipiLua.cpp]: @lrosenth 

```
[ 88%] Linking CXX executable sipiimage
Undefined symbols for architecture x86_64:
  "Sipi::MimetypeCheck::checkMimeTypeConsistency(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&)", referenced from:
      Sipi::SImage_mimetype_consistency(lua_State*) in SipiLua.cpp.o
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make[2]: *** [test/unit/sipiimage/sipiimage] Error 1
make[1]: *** [test/unit/sipiimage/CMakeFiles/sipiimage.dir/all] Error 2
make: *** [all] Error 2

```

File: src/MimetypeCheck.cpp [hunk 3]
```diff
@@ -0,0 +1,83 @@
...
+            std::string mime_from_extension = Sipi::MimetypeCheck::mimetypes.at(extension);
+
+            if (mime_from_extension != actual_mimetype) {
+                //std::cerr << "filename " << filename << "has not mime type " << actual_mimetype << std::endl;
+                return false;
+            }
+        } catch (std::out_of_range &e) {
+            std::stringstream ss;
+            ss << "Unsupported file type: \"" << filename;
+            //throw SipiImageError(__file__, __LINE__, ss.str());
```
Comment (tobiasschweizer) [inline src/MimetypeCheck.cpp]: I will define a `MimetypeCheckError`.

File: shttps/LuaServer.cpp [hunk 4]
```diff
@@ -2305,6 +2307,52 @@ namespace shttps {
...
+        std::cout << given_mimetype << std::endl;
+        std::cout << given_filename << std::endl;
+
+        // do the consistency check
+
+        bool check;
+
+        try {
+            check = Sipi::MimetypeCheck::checkMimeTypeConsistency(filepath, given_mimetype, given_filename);
+        } catch (Sipi::SipiImageError &err) {
```
Comment (tobiasschweizer) [inline shttps/LuaServer.cpp]: catch `MimetypeCheckError`

File: src/SipiLua.cpp [hunk 5]
```diff
@@ -645,7 +646,7 @@ namespace Sipi {
         bool check;
 
         try {
-            check = img->image->checkMimeTypeConsistency(*path, given_mimetype, given_filename);
+            check = MimetypeCheck::checkMimeTypeConsistency(*path, given_mimetype, given_filename);
         } catch (SipiImageError &err) {
```
Comment (tobiasschweizer) [inline src/SipiLua.cpp]: catch `MimetypeCheckError`

**Comment by tobiasschweizer** [comment]
@lrosenth I was able to move the code and add an e2e test for the new Lua function.

However, I get a massive number of warnings and I would like to look into:

> ld: warning: direct access in function 'Sipi::SipiImage::read(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, int, std::__1::shared_ptr<Sipi::SipiRegion>, std::__1::shared_ptr<Sipi::SipiSize>, bool, Sipi::_ScalingQuality)' from file 'CMakeFiles/sipiimage.dir/__/__/__/src/SipiImage.cpp.o' to global weak symbol 'tolower(int)' from file '../../../local/lib/libexiv2.a(value.cpp.o)' means the weak symbol cannot be overridden at runtime. This was likely caused by different translation units being compiled with different visibility settings.
> ld: warning: direct access in function 'Sipi::SipiImage::getDim(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, int)' from file 'CMakeFiles/sipiimage.dir/__/__/__/src/SipiImage.cpp.o' to global weak symbol 'tolower(int)' from file '../../../local/lib/libexiv2.a(value.cpp.o)' means the weak symbol cannot be overridden at runtime. This was likely caused by different translation units being compiled with different visibility settings.
> ld: warning: direct access in function 'unsigned long std::__1::__str_rfind<char, unsigned long, std::__1::char_traits<char>, 18446744073709551615ul>(char const*, unsigned long, char const*, unsigned long, unsigned long)' from file 'CMakeFiles/sipiimage.dir/__/__/__/src/SipiHttpServer.cpp.o' to global weak symbol 'std::__1::char_traits<char>::eq(char, char)' from file '../../../local/lib/libexiv2.a(exif.cpp.o)' means the weak symbol cannot be overridden at runtime. This was likely caused by different translation units being compiled with different visibility settings.
> ld: warning: direct access in function 'Sipi::SImage_write(lua_State*)' from file 'CMakeFiles/sipiimage.dir/__/__/__/src/SipiLua.cpp.o' to global weak symbol 'tolower(int)' from file '../../../local/lib/libexiv2.a(value.cpp.o)' means the weak symbol cannot be overridden at runtime. This was likely caused by different translation units being compiled with different visibility settings.
> ld: warning: direct access in function 'Sipi::SImage_send(lua_State*)' from file 'CMakeFiles/sipiimage.dir/__/__/__/src/SipiLua.cpp.o' to global weak symbol 'tolower(int)' from file '../../../local/lib/libexiv2.a(value.cpp.o)' means the weak symbol cannot be overridden at runtime. This was likely caused by different translation units being compiled with different visibility settings.
> ld: warning: direct access in function 'Sipi::MimetypeCheck::checkMimeTypeConsistency(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&)' from file 'CMakeFiles/sipiimage.dir/__/__/__/src/MimetypeCheck.cpp.o' to global weak symbol 'tolower(int)' from file '../../../local/lib/libexiv2.a(value.cpp.o)' means the weak symbol cannot be overridden at runtime. This was likely caused by different translation units being compiled with different visibility settings.
> ld: warning: direct access in function 'shttps::asciitolower(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >&)' from file 'CMakeFiles/sipiimage.dir/__/__/__/shttps/Connection.cpp.o' to global weak symbol 'tolower(int)' from file '../../../local/lib/libexiv2.a(value.cpp.o)' means the weak symbol cannot be overridden at runtime. This was likely caused by different translation units being compiled with different visibility settings.
> ld: warning: direct access in function 'shttps::ltrim(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >&)' from file 'CMakeFiles/sipiimage.dir/__/__/__/shttps/Connection.cpp.o' to global weak symbol 'isspace(int)' from file '../../../local/lib/libpodofo.a(PdfPainter.cpp.o)' means the weak symbol cannot be overridden at runtime. This was likely caused by different translation units being compiled with different visibility settings.
> ld: warning: direct access in function 'shttps::rtrim(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >&)' from file 'CMakeFiles/sipiimage.dir/__/__/__/shttps/Connection.cpp.o' to global weak symbol 'isspace(int)' from file '../../../local/lib/libpodofo.a(PdfPainter.cpp.o)' means the weak symbol cannot be overridden at runtime. This was likely caused by different translation units being compiled with different visibility settings.
> ld: warning: direct access in function 'unsigned long std::__1::__str_find_first_of<char, unsigned long, std::__1::char_traits<char>, 18446744073709551615ul>(char const*, unsigned long, char const*, unsigned long, unsigned long)' from file 'CMakeFiles/sipiimage.dir/__/__/__/shttps/LuaServer.cpp.o' to global weak symbol 'std::__1::char_traits<char>::eq(char, char)' from file '../../../local/lib/libexiv2.a(exif.cpp.o)' means the weak symbol cannot be overridden at runtime. This was likely caused by different translation units being compiled with different visibility settings.
> ld: warning: direct access in function 'shttps::Parsing::parseMimetype(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&)' from file 'CMakeFiles/sipiimage.dir/__/__/__/shttps/Parsing.cpp.o' to global weak symbol 'tolower(int)' from file '../../../local/lib/libexiv2.a(value.cpp.o)' means the weak symbol cannot be overridden at runtime. This was likely caused by different translation units being compiled with different visibility settings.
> ld: warning: direct access in function 'shttps::Parsing::parseMimetype(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&)' from file 'CMakeFiles/sipiimage.dir/__/__/__/shttps/Parsing.cpp.o' to global weak symbol 'tolower(int)' from file '../../../local/lib/libexiv2.a(value.cpp.o)' means the weak symbol cannot be overridden at runtime. This was likely caused by different translation units being compiled with different visibility settings.
> ld: warning: direct access in function 'unsigned long std::__1::__str_rfind<char, unsigned long, std::__1::char_traits<char>, 18446744073709551615ul>(char const*, unsigned long, char const*, unsigned long, unsigned long)' from file 'CMakeFiles/sipiimage.dir/__/__/__/src/SipiFilenameHash.cpp.o' to global weak symbol 'std::__1::char_traits<char>::eq(char, char)' from file '../../../local/lib/libexiv2.a(exif.cpp.o)' means the weak symbol cannot be overridden at runtime. This was likely caused by different translation units being compiled with different visibility settings.

**Comment by tobiasschweizer** [comment]
> This was likely caused by different translation units being compiled with different visibility settings

So how can we unify the visibility settings?

**Comment by tobiasschweizer** [comment]
see https://stackoverflow.com/questions/6658767/c-name-space-confusion-std-vs-vs-no-prefix-on-a-call-to-tolower

**Comment by tobiasschweizer** [comment]
@lrosenth Ping

**Comment by tobiasschweizer** [comment]
@lrosenth 

I tried to compile on macOS Catalina 10.15.5 and I got a lot of errors when compiling the google tests. Have you seen this too?

> [ 79%] Performing build step for 'gtest'
[ 12%] Building CXX object googletest/CMakeFiles/gtest.dir/src/gtest-all.cc.o
In file included from /Users/tobiasschweizer/gitreps/sipi/build/test/unit/gtest/src/gtest/googletest/src/gtest-all.cc:38:
In file included from /Users/tobiasschweizer/gitreps/sipi/build/test/unit/gtest/src/gtest/googletest/include/gtest/gtest.h:62:
In file included from /Users/tobiasschweizer/gitreps/sipi/build/test/unit/gtest/src/gtest/googletest/include/gtest/internal/gtest-internal.h:40:
/Users/tobiasschweizer/gitreps/sipi/build/test/unit/gtest/src/gtest/googletest/include/gtest/internal/gtest-port.h:854:12: error: no member named 'make_tuple' in namespace 'std'
using std::make_tuple;
      ~~~~~^
/Users/tobiasschweizer/gitreps/sipi/build/test/unit/gtest/src/gtest/googletest/include/gtest/internal/gtest-port.h:855:12: error: no member named 'tuple' in namespace 'std'
using std::tuple;
      ~~~~~^
/Users/tobiasschweizer/gitreps/sipi/build/test/unit/gtest/src/gtest/googletest/include/gtest/internal/gtest-port.h:975:3: error: deleted function definitions are a C++11 extension [-Werror,-Wc++11-extensions]
  GTEST_DISALLOW_COPY_AND_ASSIGN_(GTestLog);
  ^
/Users/tobiasschweizer/gitreps/sipi/build/test/unit/gtest/src/gtest/googletest/include/gtest/internal/gtest-port.h:694:23: note: expanded from macro 'GTEST_DISALLOW_COPY_AND_ASSIGN_'
  type(type const&) = delete;                 \
                      ^
/Users/tobiasschweizer/gitreps/sipi/build/test/unit/gtest/src/gtest/googletest/include/gtest/internal/gtest-port.h:975:3: error: deleted function definitions are a C++11 extension [-Werror,-Wc++11-extensions]
/Users/tobiasschweizer/gitreps/sipi/build/test/unit/gtest/src/gtest/googletest/include/gtest/internal/gtest-port.h:695:34: note: expanded from macro 'GTEST_DISALLOW_COPY_AND_ASSIGN_'
  type& operator=(type const&) = delete
                                 ^
/Users/tobiasschweizer/gitreps/sipi/build/test/unit/gtest/src/gtest/googletest/include/gtest/internal/gtest-port.h:1219:3: error: deleted function definitions are a C++11 extension [-Werror,-Wc++11-extensions]
  GTEST_DISALLOW_COPY_AND_ASSIGN_(Notification);
  ^
/Users/tobiasschweizer/gitreps/sipi/build/test/unit/gtest/src/gtest/googletest/include/gtest/internal/gtest-port.h:694:23: note: expanded from macro 'GTEST_DISALLOW_COPY_AND_ASSIGN_'
  type(type const&) = delete;                 \
                      ^
/Users/tobiasschweizer/gitreps/sipi/build/test/unit/gtest/src/gtest/googletest/include/gtest/internal/gtest-port.h:1219:3: error: deleted function definitions are a C++11 extension [-Werror,-Wc++11-extensions]
/Users/tobiasschweizer/gitreps/sipi/build/test/unit/gtest/src/gtest/googletest/include/gtest/internal/gtest-port.h:695:34: note: expanded from macro 'GTEST_DISALLOW_COPY_AND_ASSIGN_'
  type& operator=(type const&) = delete
                                 ^
/Users/tobiasschweizer/gitreps/sipi/build/test/unit/gtest/src/gtest/googletest/include/gtest/internal/gtest-port.h:1329:22: error: 'override' keyword is a C++11 extension [-Werror,-Wc++11-extensions]
  ~ThreadWithParam() override { Join(); }
                     ^
/Users/tobiasschweizer/gitreps/sipi/build/test/unit/gtest/src/gtest/googletest/include/gtest/internal/gtest-port.h:1338:14: error: 'override' keyword is a C++11 extension [-Werror,-Wc++11-extensions]
  void Run() override {
             ^
/Users/tobiasschweizer/gitreps/sipi/build/test/unit/gtest/src/gtest/googletest/include/gtest/internal/gtest-port.h:1353:3: error: deleted function definitions are a C++11 extension [-Werror,-Wc++11-extensions]
  GTEST_DISALLOW_COPY_AND_ASSIGN_(ThreadWithParam);
  ^
/Users/tobiasschweizer/gitreps/sipi/build/test/unit/gtest/src/gtest/googletest/include/gtest/internal/gtest-port.h:694:23: note: expanded from macro 'GTEST_DISALLOW_COPY_AND_ASSIGN_'
  type(type const&) = delete;                 \
                      ^
/Users/tobiasschweizer/gitreps/sipi/build/test/unit/gtest/src/gtest/googletest/include/gtest/internal/gtest-port.h:1353:3: error: deleted function definitions are a C++11 extension [-Werror,-Wc++11-extensions]
/Users/tobiasschweizer/gitreps/sipi/build/test/unit/gtest/src/gtest/googletest/include/gtest/internal/gtest-port.h:695:34: note: expanded from macro 'GTEST_DISALLOW_COPY_AND_ASSIGN_'
  type& operator=(type const&) = delete
                                 ^
/Users/tobiasschweizer/gitreps/sipi/build/test/unit/gtest/src/gtest/googletest/include/gtest/internal/gtest-port.h:1711:3: error: deleted function definitions are a C++11 extension [-Werror,-Wc++11-extensions]
  GTEST_DISALLOW_COPY_AND_ASSIGN_(Mutex);
  ^
/Users/tobiasschweizer/gitreps/sipi/build/test/unit/gtest/src/gtest/googletest/include/gtest/internal/gtest-port.h:694:23: note: expanded from macro 'GTEST_DISALLOW_COPY_AND_ASSIGN_'
  type(type const&) = delete;                 \
                      ^
/Users/tobiasschweizer/gitreps/sipi/build/test/unit/gtest/src/gtest/googletest/include/gtest/internal/gtest-port.h:1711:3: error: deleted function definitions are a C++11 extension [-Werror,-Wc++11-extensions]
/Users/tobiasschweizer/gitreps/sipi/build/test/unit/gtest/src/gtest/googletest/include/gtest/internal/gtest-port.h:695:34: note: expanded from macro 'GTEST_DISALLOW_COPY_AND_ASSIGN_'
  type& operator=(type const&) = delete
                                 ^
/Users/tobiasschweizer/gitreps/sipi/build/test/unit/gtest/src/gtest/googletest/include/gtest/internal/gtest-port.h:1729:3: error: deleted function definitions are a C++11 extension [-Werror,-Wc++11-extensions]
  GTEST_DISALLOW_COPY_AND_ASSIGN_(GTestMutexLock);
  ^
/Users/tobiasschweizer/gitreps/sipi/build/test/unit/gtest/src/gtest/googletest/include/gtest/internal/gtest-port.h:694:23: note: expanded from macro 'GTEST_DISALLOW_COPY_AND_ASSIGN_'
  type(type const&) = delete;                 \
                      ^
/Users/tobiasschweizer/gitreps/sipi/build/test/unit/gtest/src/gtest/googletest/include/gtest/internal/gtest-port.h:1729:3: error: deleted function definitions are a C++11 extension [-Werror,-Wc++11-extensions]
/Users/tobiasschweizer/gitreps/sipi/build/test/unit/gtest/src/gtest/googletest/include/gtest/internal/gtest-port.h:695:34: note: expanded from macro 'GTEST_DISALLOW_COPY_AND_ASSIGN_'
  type& operator=(type const&) = delete
                                 ^
/Users/tobiasschweizer/gitreps/sipi/build/test/unit/gtest/src/gtest/googletest/include/gtest/internal/gtest-port.h:1786:5: error: deleted function definitions are a C++11 extension [-Werror,-Wc++11-extensions]
    GTEST_DISALLOW_COPY_AND_ASSIGN_(ValueHolder);
    ^
/Users/tobiasschweizer/gitreps/sipi/build/test/unit/gtest/src/gtest/googletest/include/gtest/internal/gtest-port.h:694:23: note: expanded from macro 'GTEST_DISALLOW_COPY_AND_ASSIGN_'
  type(type const&) = delete;                 \
                      ^
/Users/tobiasschweizer/gitreps/sipi/build/test/unit/gtest/src/gtest/googletest/include/gtest/internal/gtest-port.h:1786:5: error: deleted function definitions are a C++11 extension [-Werror,-Wc++11-extensions]
/Users/tobiasschweizer/gitreps/sipi/build/test/unit/gtest/src/gtest/googletest/include/gtest/internal/gtest-port.h:695:34: note: expanded from macro 'GTEST_DISALLOW_COPY_AND_ASSIGN_'
  type& operator=(type const&) = delete
                                 ^
/Users/tobiasschweizer/gitreps/sipi/build/test/unit/gtest/src/gtest/googletest/include/gtest/internal/gtest-port.h:1818:5: error: deleted function definitions are a C++11 extension [-Werror,-Wc++11-extensions]
    GTEST_DISALLOW_COPY_AND_ASSIGN_(ValueHolderFactory);
    ^
/Users/tobiasschweizer/gitreps/sipi/build/test/unit/gtest/src/gtest/googletest/include/gtest/internal/gtest-port.h:694:23: note: expanded from macro 'GTEST_DISALLOW_COPY_AND_ASSIGN_'
  type(type const&) = delete;                 \
                      ^
/Users/tobiasschweizer/gitreps/sipi/build/test/unit/gtest/src/gtest/googletest/include/gtest/internal/gtest-port.h:1818:5: error: deleted function definitions are a C++11 extension [-Werror,-Wc++11-extensions]
/Users/tobiasschweizer/gitreps/sipi/build/test/unit/gtest/src/gtest/googletest/include/gtest/internal/gtest-port.h:695:34: note: expanded from macro 'GTEST_DISALLOW_COPY_AND_ASSIGN_'
  type& operator=(type const&) = delete
                                 ^
/Users/tobiasschweizer/gitreps/sipi/build/test/unit/gtest/src/gtest/googletest/include/gtest/internal/gtest-port.h:1824:40: error: 'override' keyword is a C++11 extension [-Werror,-Wc++11-extensions]
    ValueHolder* MakeNewHolder() const override { return new ValueHolder(); }
                                       ^
fatal error: too many errors emitted, stopping now [-ferror-limit=]
20 errors generated.
make[5]: *** [googletest/CMakeFiles/gtest.dir/src/gtest-all.cc.o] Error 1
make[4]: *** [googletest/CMakeFiles/gtest.dir/all] Error 2
make[3]: *** [all] Error 2
make[2]: *** [test/unit/gtest/src/gtest-stamp/gtest-build] Error 2
make[1]: *** [test/unit/CMakeFiles/gtest.dir/all] Error 2
make: *** [all] Error 2
